USE master
GO


DROP DATABASE IF EXISTS Car2Go
GO


CREATE DATABASE Car2Go
GO


USE Car2Go
GO

CREATE TABLE BRANCH( --DONE--
    B_ID VARCHAR(50) PRIMARY KEY,
	STREET_NUMBER INT,
	STREET_NAME VARCHAR(50),
	CITY VARCHAR(50),
    PROVINCE VARCHAR(50),
	POSTAL_CODE VARCHAR(20)
);

CREATE TABLE CLASSIFICATION( --DONE--
	CLASS_ID VARCHAR(50) PRIMARY KEY,
	RATE MONEY
);

CREATE TABLE CAR( --DONE--
    VIN_NUMBER VARCHAR(50) PRIMARY KEY,
	CLASS_ID VARCHAR(50),
    PLATE_NUMBER VARCHAR(15),
	MAKE VARCHAR(20),
	MODEL VARCHAR(20),
	YEAR_MADE INT,
	COLOR VARCHAR(20),
	CONSTRAINT FK_CAR_01 FOREIGN KEY (CLASS_ID) REFERENCES CLASSIFICATION(CLASS_ID)
);

CREATE TABLE CUSTOMER( --DONE--
    LICENSE_NUMBER VARCHAR(50) PRIMARY KEY,
	FIRST_NAME VARCHAR(50),
	LAST_NAME VARCHAR(50),
	STREET_NUMBER INT,
	STREET_NAME VARCHAR(50),
	UNIT_NUMBER INT,
	PROVINCE VARCHAR(50),
    CITY VARCHAR(50),
	POSTAL_CODE VARCHAR(20),
	COUNTRY VARCHAR(50)
);

CREATE TABLE PROMOTION( --DONE--
    PROMO_ID VARCHAR(50) PRIMARY KEY,
	CLASS_ID VARCHAR(50),
    PROMO_RATE INT,
	START_DATE DATE,
	END_DATE DATE,
	CONSTRAINT FK_PROMO_01 FOREIGN KEY (CLASS_ID) REFERENCES CLASSIFICATION(CLASS_ID)
);

CREATE TABLE RENTAL( --DONE--
    RENTAL_ID VARCHAR(50) PRIMARY KEY,
	VIN_NUMBER VARCHAR(50),
	LICENSE_NUMBER VARCHAR(50),
    REQUESTED_CLASSIFICATION VARCHAR(50),
    INITIAL_MILAGE INT,
	RETURN_MILAGE INT,
	RETURN_GAS_VOLUME VARCHAR(50),
	RENTAL_DATE DATE,
	RETURN_DATE DATE,
	INITIAL_B_ID VARCHAR(50),
	RETURN_B_ID VARCHAR(50),
	DROPOFF_PRICE INT,
	CONSTRAINT FK_RENTAL_01 FOREIGN KEY (LICENSE_NUMBER) REFERENCES CUSTOMER(LICENSE_NUMBER),
	CONSTRAINT FK_RENTAL_02 FOREIGN KEY (VIN_NUMBER) REFERENCES CAR(VIN_NUMBER),
	CONSTRAINT FK_RENTAL_03 FOREIGN KEY (INITIAL_B_ID) REFERENCES BRANCH(B_ID),
	CONSTRAINT FK_RENTAL_04 FOREIGN KEY (RETURN_B_ID) REFERENCES BRANCH(B_ID),
	CONSTRAINT FK_RENTAL_05 FOREIGN KEY (REQUESTED_CLASSIFICATION) REFERENCES CLASSIFICATION(CLASS_ID)
);

CREATE TABLE EMAIL(
    LICENSE_NUMBER VARCHAR(50),
	EMAIL VARCHAR(50),
	CONSTRAINT FK_EMAIL_01 FOREIGN KEY (LICENSE_NUMBER) REFERENCES CUSTOMER(LICENSE_NUMBER),
	CONSTRAINT PK_EMAIL PRIMARY KEY (LICENSE_NUMBER, EMAIL)

);

CREATE TABLE PHONE(
    LICENSE_NUMBER VARCHAR(50),
	COUNTRY_CODE INT,
	AREA_CODE INT,
	LOCAL_NUMBER INT,
	CONSTRAINT FK_PHONE_01 FOREIGN KEY (LICENSE_NUMBER) REFERENCES CUSTOMER(LICENSE_NUMBER),
	CONSTRAINT PK_PHONE PRIMARY KEY (LICENSE_NUMBER, COUNTRY_CODE, AREA_CODE, LOCAL_NUMBER)
);

SELECT * FROM BRANCH;
SELECT * FROM CLASSIFICATION;
SELECT * FROM Car;
SELECT * FROM RENTAL;
SELECT * FROM CUSTOMER;
SELECT * FROM PROMOTION;
SELECT * FROM EMAIL;
SELECT * FROM PHONE;

